### ISSUE TITLE
example file for training set

### ISSUE THREAD

**Issue by kad-ecoli** [hashemifar/DPPI#1]
It is not immediately clear what does the README file mean by "Training data: It is in dat format.Training data contains three column where first and second columns are two proteins". Similarly, it is unclear what does it mean by "Cropped profiles of proteins: It is in t7 format. This file is made using a script called ‘create_crop.lua’." Is it possible to provide small example files for training data and the expected output?

**Comment by hashemifar** [comment]
Uploaded an example :)
